spring:
  aop:
    proxy-target-class: true

zuul:
  routes:
    api:
      path: /api/**
      serviceId: project-a-api
    user:
      path: /user/**
      url: http://localhost:9999/uaa/user
    ui:
      path: /**
      serviceId: project-a-ui

security:
  user:
    password: password
  oauth2:
    client:
      accessTokenUri: http://localhost:9999/uaa/oauth/token
      userAuthorizationUri: http://localhost:9999/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
    resource:
      userInfoUri: http://localhost:9999/uaa/user

proxy:
  auth:
    routes:
      api: oauth2
      stores: passthru
      recommendations: none

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8080
