server:
  port: 8600

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

sample:
  property: Sample Property

spring:
  data:
    elasticsearch:
      properties:
        path.home: build/elastic-cluster
        transport.tcp.connect_timeout: 30s